version: '3.8'

services:
  react_app-1:
    build: .
    container_name: react_app-1
    command: npm start -- --host 0.0.0.0 --port 3000
    ports:
      - "3000"  # Solo para desarrollo, quita esto en producción
    networks:
      - react_net

  react_app-2:
    build: .
    container_name: react_app-2
    command: npm start -- --host 0.0.0.0 --port 3000
    ports:
      - "3000"  # Solo para desarrollo
    networks:
      - react_net

  nginx_balancer:
    image: nginx:alpine
    container_name: nginx_balancer_react
    ports:
      - "3001:3001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react_app-1
      - react_app-2
    networks:
      - react_net

networks:
  react_net: